Added support for simple objects in EachBinding
riot/dom-bindings pull request #23
Opened 2021-08-07 10:38 UTC by kachurun

https://github.com/riot/riot/issues/2932

2021-08-08 14:02 UTC, GianlucaGuarini requested changes
Thank you @kachurun this PR should be se `on hold` it requires core changes to the compiler. We can come here later.

2021-08-08 14:02 UTC, GianlucaGuarini commented on src/bindings/each.js
> +    const isIterable = Array.isArray(collection) || Object.getPrototypeOf(collection) === Object.prototype || Object.getPrototypeOf(collection) === null
for this check you might use something simpler like https://github.com/biancojs/is-iterable/blob/master/index.next.js#L6-L8

2021-08-08 14:02 UTC, GianlucaGuarini commented on src/bindings/each.js
> +  for (const index in items) {
I am not a big fan of `for` loops, why didn't you keep the `forEach` method? I prefer semantic and functional code over imperative patterns. It would be interesting to know also how it performs compared to the previous version (`npm run bench`)

2021-08-08 14:02 UTC, GianlucaGuarini commented on src/bindings/each.js
> +    if (!Object.prototype.hasOwnProperty.call(items, index)) {
We definitely need to move this helper here https://github.com/riot/util/blob/main/objects.js

2021-08-08 14:02 UTC, GianlucaGuarini commented on test/bindings/each.spec.js
> +      indexName: 'name',
here we are misusing the `indexName` to get the object key. We need to add a new value to the eachBinding called `keyName` for Object loops.

2021-08-14 12:20 UTC, kachurun commented on src/bindings/each.js
> +    const isIterable = Array.isArray(collection) || Object.getPrototypeOf(collection) === Object.prototype || Object.getPrototypeOf(collection) === null
Actually not, I select wrong name for that. Correct name is `isPlainArrayOrObject`😄

2021-08-14 12:28 UTC, kachurun commented on src/bindings/each.js
> +  for (const index in items) {
I'm too, but `for` is much more faster:
https://jsben.ch/Qf0M2

2021-08-14 12:36 UTC, kachurun commented on src/bindings/each.js
> +  for (const index in items) {
Hmm. Only for objects, for simple arrays forEach is faster:
https://jsben.ch/acsWA

All right, I fix code

2024-08-14 06:31 UTC, closed without merging